require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ipfsDemo' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ipfsDemoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.96.0', 'Flipper-Folly' => '~> 2.6', 'Flipper-RSocket' => '~> 1.4' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ipfsDemo-tvOS' do
  # Pods for ipfsDemo-tvOS

  target 'ipfsDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
